Laravel/livemoodle/Application/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\http\Controllers\PhotoController;
use App\http\Controllers\MatiereController;
use App\http\Controllers\ExerciceController;
use App\http\Controllers\QuestionController;
use App\http\Controllers\ClasseController;
use App\http\Controllers\UserController;
use App\http\Controllers\ImageController;

Route::middleware('guest')->group(function () {
    Route::get('/', function () {
        return view('auth/login');
    });
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

/*Reserve aux utilisateurs authentifiés*/
Route::middleware('auth')->group(
    function () {
        Route::get('image-upload',[ImageController::class, 'image_upload'])->name('image.upload');
        Route::post('image-upload',[ImageController::class, 'upload_post_image'])->name('upload.post.image');

        Route::resource('users', UserController::class);
        Route::Post('classe/{id}/store', [UserController::class, 'store'])->name('users.classe.store');
        Route::get('classe/{slug}/users', [UserController::class, 'index'])->name('users.classe');

        Route::resource('matieres', MatiereController::class);
        Route::get('matieres/{matiere}/', [MatiereController::class, 'gestionclasse'])->name('gestionclasse');

        Route::resource('matieres.exercices', ExerciceController::class)->middleware('AccesMiddleware');
        Route::resource('exercices', ExerciceController::class, ['only' => ['edit', 'update']]);
        Route::get('matiere/{slug}/exercices', [ExerciceController::class, 'index'])->name('exercices.matiere')->middleware('AccesMiddleware');
        Route::put('/updateEtat', [ExerciceController::class, 'updateEtat']);
        Route::put('/updateExercice', [ExerciceController::class, 'updateChrono']);
        Route::get('exercices/exercice', [ExerciceController::class, 'exercice']);
        Route::resource('exercices.classes', ExerciceController::class, ['only' => ['show']]);

        Route::resource('exercices.users.questions', QuestionController::class)->middleware('QuestionMiddleware');
        Route::get('/stop/{id}/{slug}/', [QuestionController::class, 'stop'])->name('stop');
        Route::resource('questions', QuestionController::class, ['only' => ['edit', 'update']]);
        Route::get('reponses/reponse', [QuestionController::class, 'reponse']);
        Route::get('reponses/tableau', [QuestionController::class, 'tableau']);
        Route::put('/updateReponse', [QuestionController::class, 'updateReponse']);
        Route::put('/updateTab', [QuestionController::class, 'updateTab']);
        Route::put('/updateTemps', [QuestionController::class, 'updateTemps']);
        
        Route::resource('classes', ClasseController::class);
        Route::get('classe/{classe}/{exercice}/', [ClasseController::class, 'listeclasse'])->name('listeclasse');
    }
);

Laravel/livemoodle/Application/app/Models/Classe.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Classe extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nom'
    ];

    /*BelongsTo (user)*/ 
    public function user(){
        return $this->hasMany(User::class);
    }

    public function faitpartie(){
        return $this->belongsToMany('App\Models\Matiere');
    }

    public function isAjouter($id_matiere){

            return Classe::find($this->id)->faitpartie->contains('id', $id_matiere);
    }
}

Laravel/livemoodle/Application/app/Http/Controllers/ClasseController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Models\Classe;
use App\Models\Exercice;
use App\Models\User;
use App\Models\Matiere;
use App\Http\Requests\Classe as ClasseRequest;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\UpdateClasseRequest as updateClasseRequest;

class ClasseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware(['roleChecker:prof,null']);
    }
    public function index()
    {
        $classes = Classe::oldest('nom')->paginate(5);
        return view('classe\index', compact('classes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('classe\create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ClasseRequest $classerequest)
    {
        $classe = new Classe;
        $classe->nom = $classerequest->nom;
        $classe->slug = Str::slug($classe->nom);
        $classe->save();

        return redirect()->route('classes.index')->with('info', 'classe créée');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($classe)
    {
        $users = User::all();
        return view('classe\show', compact('classe', 'users'));
    }

    public function listeclasse($idmatiere, $idexercice)
    {
        $exercice = Exercice::findOrFail($idexercice);
        $matieres_classes = DB::table('classe_matiere')->where('matiere_id', $idmatiere)->get();
        if (!$matieres_classes->isEmpty()) {
            $i = 0;
            foreach ($matieres_classes as $matiere_classe) {
                $classe_id_array[$i] = $matiere_classe->classe_id;
                $i++;
            }
            $classes = Classe::whereIn('id', $classe_id_array)->get();
        } else {
            $classes = null;
        }
        $matiere = Matiere::find($exercice->matiere_id);
        return view('classe\listeclasse', compact('classes', 'exercice', 'matiere'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $classe = Classe::findOrFail($id);
        return view('classe\edit', compact('classe'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(updateClasseRequest $classerequest, $id)
    {
        $classe = Classe::findOrFail($id);
        $classe->update($classerequest->all());
        return redirect()->route('classes.index')->with('info', 'La classe a bien été modifié');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('users')->where('classe_id', $id)->update(['classe_id' => null]);
        $classe = Classe::findOrFail($id);
        $classe->delete();
        return back()->with('info', 'La classe a bien été supprimé dans la base de données.');
    }
}

Laravel/livemoodle/Application/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

Laravel/livemoodle/Application/resources/views/classe/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
           Creation classe
        </h2>
    </x-slot>

    <div>
        <div class="max-w-4xl mx-auto py-10 sm:px-6 lg:px-8">
            <div class="mt-5 md:mt-0 md:col-span-2">
                <div class="block mb-8">
                    <a href="{{ route('classes.index') }}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Retour</a>
                </div>
                <form method="post" action="{{ route('classes.store') }}">
                    @csrf
                    <div class="shadow overflow-hidden sm:rounded-md">
                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="nom" class="block font-medium text-sm text-gray-700">Nom</label>
                            <input type="text" name="nom" id="nom" class="form-input rounded-md shadow-sm mt-1 block w-full"/>
                            @error('nom')
                                <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="flex items-center justify-end px-4 py-3 bg-gray-50 text-right sm:px-6">
                            <button class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150">
                                Creer
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

Laravel/livemoodle/Application/resources/views/classe/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Modifier classe
        </h2>
    </x-slot>

    <div>
        <div class="max-w-4xl mx-auto py-10 sm:px-6 lg:px-8">
            <div class="block mb-8">
                <a href="{{ route('classes.index') }}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Retour</a>
            </div>
            <div class="mt-5 md:mt-0 md:col-span-2">
                <form method="post" action="{{ route('classes.update', $classe->id) }}">
                    @csrf
                    @method('PUT')
                    <div class="shadow overflow-hidden sm:rounded-md">
                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="nom" class="block font-medium text-sm text-gray-700">Nom</label>
                            <input type="text" name="nom" id="nom" class="form-input rounded-md shadow-sm mt-1 block w-full" value="{{ old('nom', $classe->nom) }}"/>
                            @error('nom')
                                <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="flex items-center justify-end px-4 py-3 bg-gray-50 text-right sm:px-6">
                            <button class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150">
                                Modifier
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

Laravel/livemoodle/Application/resources/views/classe/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Classe
        </h2>
    </x-slot>

    <div>
        <div class="max-w-6xl mx-auto py-10 sm:px-6 lg:px-8">
            @if(Auth::user()->role=='prof')
                <div class="block mb-8">
                    <a href="{{ route('classes.create') }}" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Ajouter classe</a>
                    <a href="{{ route('dashboard') }}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Retour</a>
                </div>
            @endif
            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200 w-full">
                                <thead>
                                <tr>
                                    <th scope="col" width="50" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        NOM
                                    </th>
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Gestion
                                    </th>
                                </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                @if($classes->isEmpty())
                                    <tr>
                                        <td></td>
                                        <td>
                                            Il n'y a encore auccune classe, vous devez les creer pour y ajouter des étudiants
                                        </td>
                                    </tr>
                                @else
                                    @foreach ($classes as $classe)
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                            <a href="{{ route('users.classe', $classe->slug) }}" class="text-blue-600 hover:text-blue-900 mb-2 mr-2">{{$classe->nom}}</a>
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                                                <a href="{{ route('classes.edit', $classe->id) }}" class="text-indigo-600 hover:text-indigo-900 mb-2 mr-2">Modifier</a>
                                                <form class="inline-block" action="{{ route('classes.destroy', $classe->id) }}" method="POST" onsubmit="return confirm('Vous etes sur ?');">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <input type="submit" class="text-red-600 hover:text-red-900 mb-2 mr-2" value="Supprimer">
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <footer class="card-footer">
            {{ $classes->links() }}
        </footer>
        </div>
    </div>
</x-app-layout>

Laravel/livemoodle/Application/resources/views/classe/listeclasse.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Liste des classes inscrits a la matiere
        </h2>
    </x-slot>

    <div>
        <div class="max-w-6xl mx-auto py-10 sm:px-6 lg:px-8">
            <div class="block mb-8">
                <a href="{{ route('matieres.exercices.index',$matiere->slug) }}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Retour</a>
            </div>
            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200 w-full">
                                <thead>
                                <tr>
                                    <th scope="col" width="50" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Classes
                                    </th>
                                </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                    @if($classes != null)
                                        @foreach ($classes as $classe)
                                            <tr>
                                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                                    <a href="{{ route('exercices.classes.show', [$exercice->id, $classe->id]) }}"class="text-blue-600 hover:text-blue-900 mb-2 mr-2">{{$classe->nom}}</a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @else
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                                Auccune classe n'est inscrit à ce cours
                                            </td>
                                        </tr>
                                    @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</x-app-layout>

Laravel/livemoodle/Application/resources/views/classe/show.blade.php
<x-app-layout>
    <div class="card">
    <header class="card-header">
    </header>
        <div class="max-w-6xl mx-auto py-10 sm:px-6 lg:px-8">
            <div class="block mb-8">
                <a href="{{ route('classes.index') }}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Retour</a>
            </div>
            <div class="block mb-8">
                @livewire('rechercheetudiant')
            </div> 
            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200 w-full">
                                <thead>
                                <tr>
                                <th scope="col" width="50" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        NOM 
                                    </th>
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Mail
                                    </th>
                                </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                @foreach ($users as $user)
                                    <tr>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                            {{ $user->name }}
                                        </td>

                                        <td class=" text-sm text-gray-900">
                                            {{ $user->email }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                                            <form class="inline-block" action="{{ route('users.destroy', $user->id) }}" method="POST" onsubmit="return confirm('Vous etes sur ?');">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <input type="submit" class="text-red-600 hover:text-red-900 mb-2 mr-2" value="Supprimer">
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <style>
    select, .is-info {
        margin: 0.3em;
    }
</style>
</x-app-layout>