Laravel/livemoodle/Application/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\http\Controllers\PhotoController;
use App\http\Controllers\MatiereController;
use App\http\Controllers\ExerciceController;
use App\http\Controllers\QuestionController;
use App\http\Controllers\ClasseController;
use App\http\Controllers\UserController;
use App\http\Controllers\ImageController;

Route::middleware('guest')->group(function () {
    Route::get('/', function () {
        return view('auth/login');
    });
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

/*Reserve aux utilisateurs authentifiés*/
Route::middleware('auth')->group(
    function () {
        Route::get('image-upload',[ImageController::class, 'image_upload'])->name('image.upload');
        Route::post('image-upload',[ImageController::class, 'upload_post_image'])->name('upload.post.image');

        Route::resource('users', UserController::class);
        Route::Post('classe/{id}/store', [UserController::class, 'store'])->name('users.classe.store');
        Route::get('classe/{slug}/users', [UserController::class, 'index'])->name('users.classe');

        Route::resource('matieres', MatiereController::class);
        Route::get('matieres/{matiere}/', [MatiereController::class, 'gestionclasse'])->name('gestionclasse');

        Route::resource('matieres.exercices', ExerciceController::class)->middleware('AccesMiddleware');
        Route::resource('exercices', ExerciceController::class, ['only' => ['edit', 'update']]);
        Route::get('matiere/{slug}/exercices', [ExerciceController::class, 'index'])->name('exercices.matiere')->middleware('AccesMiddleware');
        Route::put('/updateEtat', [ExerciceController::class, 'updateEtat']);
        Route::put('/updateExercice', [ExerciceController::class, 'updateChrono']);
        Route::get('exercices/exercice', [ExerciceController::class, 'exercice']);
        Route::resource('exercices.classes', ExerciceController::class, ['only' => ['show']]);

        Route::resource('exercices.users.questions', QuestionController::class)->middleware('QuestionMiddleware');
        Route::get('/stop/{id}/{slug}/', [QuestionController::class, 'stop'])->name('stop');
        Route::resource('questions', QuestionController::class, ['only' => ['edit', 'update']]);
        Route::get('reponses/reponse', [QuestionController::class, 'reponse']);
        Route::get('reponses/tableau', [QuestionController::class, 'tableau']);
        Route::put('/updateReponse', [QuestionController::class, 'updateReponse']);
        Route::put('/updateTab', [QuestionController::class, 'updateTab']);
        Route::put('/updateTemps', [QuestionController::class, 'updateTemps']);
        
        Route::resource('classes', ClasseController::class);
        Route::get('classe/{classe}/{exercice}/', [ClasseController::class, 'listeclasse'])->name('listeclasse');
    }
);

Laravel/livemoodle/Application/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'role',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    public function likes(){
        return $this->belongsToMany('App\Models\Matiere');
    }

    /*BelongsTo (matiere)*/
    public function matiere(){
        return $this->belongsTo(Matiere::class);
    }

    public function classe()
    {
        return $this->belongsTo(Classe::class);
    }

    public function reponses(){
        return $this->belongsToMany(Reponse::class);
    }

    public function tableau(){
        return $this->belongsToMany(Tableau::class);
    }
}

Laravel/livemoodle/Application/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Classe;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Session;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(){
        $this->middleware(['roleChecker:prof,null']);
    }

    public function index($slug = null)
    {
        $query = $slug ? Classe::whereSlug($slug)->firstOrFail()->user() : Classe::query();
        $users = $query->paginate(10); 
        $user_all=DB::table('users')->where('classe_id',null)
                                    ->get();
        $classe =  Classe::whereSlug($slug)->get();
        return view('user\index', compact('users','classe','user_all','slug'));
    }

    public function store($id_classe,Request $request){
    $input=$request->all();
    if(isset($input['etudiant'])!=false){
        $etudiants=$input['etudiant'];
        foreach($etudiants as $etudiant_id){
            $etudiant=User::find($etudiant_id);
            $etudiant->classe_id=$id_classe;
            $etudiant->update();
        }
    }else{
        Session::flash('message', "vous essayé d'ajouter un etudiant qui n'exisite pas !");
    }
    return back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, $id2)
    {
       return back()->with('info', 'Eleve ajoute a la classe.');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->classe_id = null;
        $user->save();
        return back()->with('info', 'Eleve supprime de la classe.');
    }
}

Laravel/livemoodle/Application/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

Laravel/livemoodle/Application/resources/views/user/index.blade.php
   
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        @foreach($classe as $c)
           {{$c->nom}}
    </x-slot>
         @endforeach
        <div class="max-w-6xl mx-auto py-10 sm:px-6 lg:px-8">
            <div class="block mb-8">
                <a href="{{ route('classes.index') }}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Retour</a>
                @if(Auth::user()->role=='prof')
                    <button data-toggle="modal" data-target="#infos" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-2 rounded">?</button>
                    <div class="modal" id="infos">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Informations</h4>
                                    <button type="button" class="close" data-dismiss="modal">
                                    <span>&times;</span>
                                    </button>            
                                </div>
                                <div class="modal-body">
                                    Ici vous accedez à la liste des etudiants de cette classe. 
                                    Vous pouvez en ajouter des etudiants en les cherchants ou en entrant leur mail etudiant.
                                </div>
                            </div>
                        </div>
                    </div>
                @endif
            </div>
            <div class="container">
                <div class="row">
                    <div class="col">
                            <form method="post" action="{{route('users.classe.store',['id'=>$c->id])}}" enctype="multipart/form-data">
                                    @csrf
                                        <label><strong>Liste etudiants:</strong></label><br/>
                                        @if($user_all->isEmpty())
                                            Il n'y a pas d'etudiant
                                        @else
                                            <select class="selectpicker" multiple data-live-search="true" name="etudiant[]">
                                            @foreach ($user_all as $u)
                                                {{$val=$u->id}}
                                                @if ($u->role == 'eleve')
                                                    <option value="{{$val}}">{{$u->email}}</option>
                                                @endif
                                            @endforeach
                                        
                                        </select>
                                        <!-- Send button -->
                                        <button class="btn btn-primary" type="submit">Ajouter</button> 
                                    @endif         
                        </form>
                    </div>
                </div>
            </div> 
            @if (Session::has('message'))
                <div class="alert alert-info color red" style="color: #d11a1a;">vous essayez d'ajouter un etudiant qui n'existe pas !</div>           
            @endif
        <br>
            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200 w-full">
                                <thead>
                                    <tr>
                                        <th scope="col" width="50" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            NOM
                                        </th>
                                        <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Mail
                                        </th>
                                        <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Gestion
                                        </th>
                                    </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                    @if($users->isEmpty())
                                        <tr>
                                            <td></td>
                                            <td>
                                                Il n'y a encore auccun étudiant dans cette classe, 
                                                vous devez en ajouter pour qu'ils repondent aux exercices
                                            </td>
                                        </tr>
                                    @else
                                        @foreach ($users as $user)
                                            <tr>
                                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                                    {{ $user->name }}
                                                </td>

                                                <td class=" text-sm text-gray-900">
                                                    {{ $user->email }}
                                                </td>
                                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                                                    <form class="inline-block" action="{{ route('users.destroy', $user->id) }}" method="POST" onsubmit="return confirm('Vous etes sur ?');">
                                                        <input type="hidden" name="_method" value="DELETE">
                                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                        <input type="submit" class="text-red-600 hover:text-red-900 mb-2 mr-2" value="Supprimer">
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <footer class="card-footer">
                {{ $users->links() }}
            </footer>
        </div>
    <style>
        select, .is-info {
            margin: 0.3em;
        }
    </style>
</x-app-layout>