Laravel/urclan/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
   // return view('welcome');
// });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/',function(){
	$infoLan = DB::table('info_lans')->select('id','description','name','twitter','facebook','discord')->get();
		
		if (Auth::check()) {
			if($infoLan != '[]')
			{
				return view('welcome');
			}else{
				return redirect()->route('home')->with('erreur', 'Remplissez les champs dans gestion Lan !');
			}
		}else{
			if($infoLan != '[]')
			{
				return view('welcome');
			}else{
				return redirect()->route('login')->with('status', 'Connectez-vous en admin et remplissez les champs dans gestion Lan !');
			}
		}
});


Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function() {
	Route::resource('users','UsersController');
	Route::resource('infolans','InfoLanController');
	Route::post('infolans','InfoLanController@store');
});

Route::namespace('Orga')->prefix('orga')->name('orga.')->middleware('can:manage-users')->group(function() {
	Route::resource('materiels','MaterielController');
});

Route::namespace('Orga')->prefix('orga')->name('orga.')->middleware('can:seetaches')->group(function() {
	Route::resource('taches','TacheController');
	Route::post('taches','TacheController@store');
});


Route::namespace('Orga')->prefix('orga')->name('orga.')->middleware('can:seetournois')->group(function() {
	Route::resource('tournois','TournoiController');
});

Route::namespace('Orga')->prefix('orga')->name('orga.')->group(function() {
	Route::resource('games','GameController');
});

Route::namespace('Orga')->prefix('orga')->name('orga.')->middleware('can:seeclassements')->group(function() {
	Route::post('classements','ClassementController@store');
	Route::resource('classements','ClassementController');
	Route::resource('scores','ScoreController');
});

Route::namespace('Player')->prefix('player')->name('player.')->group(function() {
	Route::resource('equipes','EquipesController');
});

Route::namespace('Player')->prefix('player')->name('player.')->group(function() {
	Route::resource('equipes','EquipesController');
});

Route::get('profile','UserController@profile');
Route::post('profile','UserController@update_avatar');
Route::post('/modification-mot-de-passe','UserController@modificationMotDePasse');

Laravel/urclan/app/Game.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    protected $fillable = [
    	'name', 'version', 'portReseau', 'description'
    ];
}

Laravel/urclan/app/Http/Controllers/Orga/AideController.php
<?php

namespace App\Http\Controllers\Orga;

use App\Aide;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AideController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Aide  $aide
     * @return \Illuminate\Http\Response
     */
    public function show(Aide $aide)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Aide  $aide
     * @return \Illuminate\Http\Response
     */
    public function edit(Aide $aide)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Aide  $aide
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Aide $aide)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Aide  $aide
     * @return \Illuminate\Http\Response
     */
    public function destroy(Aide $aide)
    {
        //
    }
}

Laravel/urclan/app/Http/Controllers/Orga/ClassementController.php
<?php

namespace App\Http\Controllers\Orga;

use App\Classement;
use App\Tournoi;
use App\Score;
use App\Equipe;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use DataTables;

class ClassementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $classements = Classement::latest()->paginate(5);
        $tournois = Tournoi::all();

        return view('orga.classements.index', compact('tournois', 'classements'))->with('i',(request()->input('page',1)-1)*5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required|unique:classements',
            'tournoi_id' => 'required',
        ]);

        $name = request('name');
        $tournoi_id = request('tournoi_id');

        $classement = new Classement();
        $classement->name = $name;
        $classement->tournoi_id = $tournoi_id;
        $classement->save();

        return back()->with('add','Classement add !');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Classement  $classement
     * @return \Illuminate\Http\Response
     */
    public function show(Classement $classement)
    {
        return view('orga.classements.show', compact('classement'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Classement  $classement
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Classement  $classement
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Classement $classement)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Classement  $classement
     * @return \Illuminate\Http\Response
     */
    public function destroy(Classement $classement)
    {
        $tournoi = $classement->tournoi;
        $equipe = $tournoi->equipes;
        foreach ($equipe as $key) {
            $key->score->update(['victoire' => '0','defaite' => '0']);
        }
        
        $classement->delete();
  
        return redirect()->route('orga.classements.index')->with('success','Classement supprimé !');
    }
}

Laravel/urclan/app/Http/Controllers/Orga/GameController.php
<?php

namespace App\Http\Controllers\Orga;

use App\Game;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class GameController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    	$games = Game::latest()->paginate(4);

    	return view('orga.games.index',compact('games'))->with('i',(request()->input('page',1)-1)*4);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('orga.games.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    	$request->validate([
            'name' => 'required|unique:games',
            'version' => 'required',
            'portReseau' => 'required',
            'description' => 'required',
        ]);

        Game::create($request->all());
   
        return redirect()->route('orga.games.index')->with('success','Game added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Game  $game
     * @return \Illuminate\Http\Response
     */
    public function show(Game $game)
    {
        return view('orga.games.show',compact('game'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Game  $game
     * @return \Illuminate\Http\Response
     */
    public function edit(Game $game)
    {
        return view('orga.games.edit',compact('game'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Game  $game
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Game $game)
    {
        $request->validate([
            'name' => 'required',
            'version' => 'required',
            'portReseau' => 'required',
            'description' => 'required',
        ]);
  
        $game->update($request->all());

        return redirect()->route('orga.games.index')->with('success','game updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Game  $game
     * @return \Illuminate\Http\Response
     */
    public function destroy(Game $game)
    {
        $game->delete();
  
        return redirect()->route('orga.games.index')->with('add','Game deleted successfully');
    }
}

Laravel/urclan/app/Http/Controllers/Orga/MaterielController.php
<?php

namespace App\Http\Controllers\Orga;

use App\Http\Controllers\Controller;
use App\Materiel;
use Illuminate\Http\Request;

class MaterielController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $materiels = Materiel::latest()->paginate(10);

        return view('orga.materiels.index',compact('materiels'))->with('i',(request()->input('page',1)-1)*10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(empty(request('name2')) || empty(request('quantite2'))){

        if(empty(request('name2')) && empty(request('quantite2')))
        {
            request()->validate([
            'name' => 'required|max:25',
            'quantite' => 'required',
        ]);

        }else if(empty(request('quantite2')))
        {
            request()->validate([
            'quantite' => 'required',
        ]);

        }else if(empty(request('name2'))){
            request()->validate([
            'name' => 'required|max:25',
        ]);

        }
            $name = request('name');
            $quantite = request('quantite');

        }else{

            $name = request('name2');
            $quantite = request('quantite2');
        }

        
        $description = request('description');

        $materiel = new Materiel();
        $materiel->name = $name;
        $materiel->quantite = $quantite;
        $materiel->description = $description;

        $materiel->save();

        return back()->with('add','Achat add !');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Materiel  $materiel
     * @return \Illuminate\Http\Response
     */
    public function show(Materiel $materiel)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Materiel  $materiel
     * @return \Illuminate\Http\Response
     */
    public function edit(Materiel $materiel)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Materiel  $materiel
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Materiel $materiel)
    {
        $quantite = request('quantite');
        if($quantite == 0){
            $materiel->etat=1;
        }

        $materiel->quantite = $quantite;
        $materiel->save();

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Materiel  $materiel
     * @return \Illuminate\Http\Response
     */
    public function destroy(Materiel $materiel)
    {
        $materiel->delete();

        return back()->with('success','Materiel supprimé !');
    }
}

Laravel/urclan/app/Http/Controllers/Orga/ScoreController.php
<?php

namespace App\Http\Controllers\Orga;

use App\Http\Controllers\Controller;
use App\Score;
use Illuminate\Http\Request;

class ScoreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Score  $score
     * @return \Illuminate\Http\Response
     */
    public function show(Score $score)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Score  $score
     * @return \Illuminate\Http\Response
     */
    public function edit(Score $score)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Score  $score
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Score $score)
    {
        $victoire = request('victoire');
        $defaite = request('defaite');

        $score->victoire = $victoire;
        $score->defaite = $defaite;
        $score->save();

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Score  $score
     * @return \Illuminate\Http\Response
     */
    public function destroy(Score $score)
    {
        //
    }
}

Laravel/urclan/app/Http/Controllers/Orga/TacheController.php
<?php

namespace App\Http\Controllers\Orga;

use App\Http\Controllers\Controller;
use App\Tache;
use Illuminate\Http\Request;

class TacheController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $taches = Tache::latest()->paginate(5);
        $user = auth()->user();

        return view('orga.taches.index',compact('taches','user'))->with('i',(request()->input('page',1)-1)*5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required|unique:taches',
            'description' => 'required',
            'user_id' => 'required',
        ]);
        $name = request('name');
        $description = request('description');
        $user_id = request('user_id');

        $tache = new Tache();
        $tache->name = $name;
        $tache->description = $description;
        $tache->user_id = $user_id;
        $tache->save();

        return back()->with('add','Tache add !');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tache  $tache
     * @return \Illuminate\Http\Response
     */
    public function show(Tache $tache)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tache  $tache
     * @return \Illuminate\Http\Response
     */
    public function edit(Tache $tache)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tache  $tache
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tache $tache)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tache  $tache
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tache = Tache::find($id);
        $tache->delete();
  
        return redirect()->route('orga.taches.index')->with('success','Tache supprimé !');
    }
}

Laravel/urclan/resources/views/orga/games/create.blade.php
@extends('layouts.app')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Erreur !</strong> Verifiez vos informations<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
<div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
        <div class="pull-left">
            <h1>Create New Game</h1>
        </div>
    </div>
</div>
       <div id="div-gen" class="col-xs-12 col-sm-12 col-md-12">
    <form action="{{ route('orga.games.store') }}" method="POST">
        @csrf
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <p class="text-pa"> Nom :</p>
                    <input type="text" name="name" id="input-text" class="form-control" placeholder="Nom">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <p class="text-pa">Version :</p>
                    <input type="number" name="version" id="input-text" class="form-control" placeholder="Port reseau">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <p class="text-pa">Port réseau :</p>
                    <input type="number" name="portReseau" id="input-text"  class="form-control" placeholder="Nombres d'inscriptions">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <p class="text-pa">Description :</p>
                    <textarea class="form-control" id="input-text" style="height:180px" name="description" placeholder="Description"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <a href="{{ route('orga.games.index') }}"><button type="button" class="btn btn-secondary" data-dismiss="modal">Retour</button></a>

                    <button id="btn-submit" type="submit" class="btn btn-primary">Valider</button>
                    
            </div>

        </div>
    </form>
        </div> 
@endsection

Laravel/urclan/resources/views/orga/games/edit.blade.php
@extends('layouts.app')

@section('css')
<style>
body{
    margin:0;
    padding:0;
    background: lightgrey;
    min-height: 100vh;
}
#input-text{
    background: #F2EFEF;
}
h2{
    font-family:Times New Roman;
    font-size:50px;
}
h1{
  margin: 0;
  padding: 5% 25% 5% 45%;
  font-size: 300%;
}
#div-gen{
    background: lightgrey;
    padding: 5% 15%;
}
.btn-warning {
  /* détails du bouton noir*/
  color:white;
  background-color: black;
  font-size: 16px;
  padding: 12px 24px;
  border: none;
  cursor: pointer;
  border-radius: 5px;
  text-align: center;
}
.btn:hover {
  /* change la couleur des boutons lorsqu'on pose la souris dessus*/
  background-color: orange;
  color:white;
}
.text-pa{
    color:white;
}
#div-edit{
    background: lightgrey;
    text-align: center;
}
#h2_edit{
    color: black;
}


</style>
@endsection
@section('content')
    <div id="div-edit" class="col-xs-12 col-sm-12 col-md-12">
        <h2 id="h2-edit">Editez game</h2>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
        <strong>Erreur !</strong> Verifiez vos informations<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
        <div id="div-gen" class="col-xs-12 col-sm-12 col-md-12">
    <form action="{{ route('orga.games.update',$game->id) }}" method="POST">
        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <p class="text-pa"> Nom :</p>
                    <input type="text" id="input-text" name="name" value="{{ $game->name }}" class="form-control">
                </div>
            </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <p class="text-pa">Version :</p>
                <input type="number" id="input-text" name="version" value="{{ $game->version }}" class="form-control">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <p class="text-pa">Port réseau :</p>
                <input type="number" id="input-text" name="portReseau" value="{{ $game->portReseau }}" class="form-control">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <p class="text-pa">Description :</p>
                    <textarea id="input-text" class="form-control" style="height:180px" name="description">{{ $game->description }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <a class="btn btn-warning" href="{{ route('orga.games.index') }}"> Retour</a>
              <button id="btn-submit" type="submit" class="btn btn-warning">Valider</button>
            </div>
        </div>
    </form>
        </div> 
@endsection

Laravel/urclan/resources/views/orga/games/index.blade.php
@extends('layouts.app')
@section('css')
<style>
body{
    text-decoration: none;
    min-height: 100vh;
}
#input-text{
    background: #F2EFEF;
}
#div-gen{
    padding: 5% 15%;
}
#div-check-all-games{
    text-align: center;
    margin-top: 5%;
}
#btn-submit{
    margin: 16% 5%;
    padding: 3% 8%; 
}
#div-card{
    background: #F2EFEF ;
    font-size:150%;
    height: 250px;
    margin: 4.9%;
}
#card-h5{
    color: black;
    text-align: center;
    margin: 5% 2%;
}
#card-p{
    color: black;
    text-align: center;
    margin: 10% 2% 0 2%;
}
#a-show{
    margin: 16% 5%;
    padding: 3% 6%;
}
h1{
    font-size: 300%;
}
#div-btn-add{
    padding-top: 1%;
}

#center-div{
    margin:0 auto;
    width: 100px;
}

</style>
@endsection
@section('content')



    <div id="div-check-all-games" class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <div class="pull-left">
                <h1>Games</h1>
            </div>
            @can('manage-users')
            <div id="div-btn-add" class="pull-right">
                <a class="btn btn-primary" href="{{ route('orga.games.create') }}"> Ajouter un game</a>
            </div>
            @endcan
        </div>
    </div>
    @if (session('success'))
    <div class="alert alert-dismissible alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h4 class="alert-heading">Success!</h4>
        {{ session('success') }}
    </div>
    @endif
    @if (session('add'))
    <div class="alert alert-dismissible alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h4 class="alert-heading">Success!</h4>
        {{ session('add') }}
    </div>
    @endif

    <div id="div-flex" class="d-flex flex-wrap">

    @foreach ($games as $game)

        <div id="div-card" class="card" style="width: 18rem;">
        
            <div class="card-body">
                
                <h5 id="card-h5" class="card-title">{{ $game->name }}</h5>

                <p id="card-p" class="card-text">version : {{ $game->version }}</p>

               
                <form action="{{ route('orga.games.destroy',$game->id) }}" method="POST">
                    <a id="a-show" class="btn btn-success" href="{{ route('orga.games.show',$game->id) }}">
                    <i class="far fa-eye"></i>
                    </a>
                     @can('manage-users')
                    <a id="a-show" class="btn btn-warning" href="{{ route('orga.games.edit',$game->id) }}">
                    <i class="far fa-edit"></i>
                    </a>

                    @csrf
                    @method('DELETE')

                    <button type="submit" class="btn btn-danger" id="a-show">
                    <i class="far fa-trash-alt"></i>
                    </button>
                </form>
                @endcan
            </div>
        </div>
    @endforeach
    </div>

  <script type="text/javascript">
      document.addEventListener('DOMContentLoaded', () => {
        (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
            $notification = $delete.parentNode;

            $delete.addEventListener('click', () => {
                $notification.parentNode.removeChild($notification);
            });
        });
    });
  </script>

  <div id="center-div">{{ $games->links() }}</div>
            
      
@endsection

Laravel/urclan/resources/views/orga/games/show.blade.php
@extends('layouts.app')
@section('css')
    <style>
        body{
           background: url("/img/esportv2.png");
            text-decoration: none;
            width: auto;
            background-size: cover;
            align-items: center;
            background-attachment: fixed;
        }

        .row{
            padding-top: 200px;;
        }
        .btn:hover{
            color: white;
            background-color: deepskyblue;
        }
        .pull-right{
            margin-top: 80px;
        }

        h2{
            font-weight: bold;
            font-family: Bookman, URW Bookman L, serif;
        }

        p{
            font-family: Bookman, URW Bookman L, serif;
            color: white;
        }

    </style>
@endsection
@section('content')
    <!-- *********** Presentation ************ -->
    <div class="container" id="pres">
        <div class="row">
            <div class="col-12 mb-4"><h2>Qu'est ce que {{ $game->name }}  ?</h2></div>
            <div class="col-12 col-md-6">
                <br><br>
                <div class="media">
                    <span><i class="fas fa-gamepad"></i></span>
                    <div class="media-body ml-3">
                        <h5><strong><u> Présentation </u></strong></h5>
                        <p class="text-justify">{{ $game->description }}</p>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <br><br>
                <div class="media">
                    <span><i class="fas fa-network-wired"></i></span>
                    <div class="media-body ml-3">
                        <h5><strong><u> Réseau </u></strong></h5>
                        <p class="text-justify"><strong> Version : </strong>{{ $game->version }}<br><strong> Port Réseau : </strong>{{ $game->portReseau }}</p>
                    </div>
                </div>
            </div>
            <div class="pull-right">
                <br><br><br>
                <a class="btn btn-primary" href="{{ route('orga.games.index') }}">Retour</a>
                <a href="{{ route('home') }}"><button type="button" class="btn btn-secondary" data-dismiss="modal">Page home</button></a>
            </div>
        </div>
    </div>
@endsection